language: clojure
script: 
  # get latest version of leiningen
  # travis's lein2 does not support cljc source
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -O ./lein
  - chmod +x ./lein
  - ./lein test-cljc
